//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationShipsExample.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Schelude
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schelude()
        {
            this.MoviePerCinema = new HashSet<MoviePerCinema>();
        }
    
        public int ScheludeId { get; set; }
        [Display(Name = "Cambio")]
        public int Shift { get; set; }
        [Display(Name = "Programación")]
        public string Scheludes { get; set; }
        public Nullable<int> Cinema_CinemaId { get; set; }
        public Nullable<int> Day_DayId { get; set; }
        public Nullable<int> Room_RoomId { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Day Day { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoviePerCinema> MoviePerCinema { get; set; }
        public virtual Room Room { get; set; }
    }
}
